In [18]:
#創建關係矩陣
# %%
import pandas as pd
import numpy as np
from tqdm import tqdm
import sys
import re

#讀檔
inpath = 'C:\\Users\\lol\\Desktop\\新北市七區研究\\新北市資料七區空間遞延\\板橋空間遞延\\50M\\關係矩陣\\a3 w50M.csv'
df = pd.read_csv(inpath)

#用[]list 命名['i']、['j']、['wij']
df = df[['i','j','wij']]

#將panda的Series形式轉成 list的形式 使用.to_list()
i = df['i'].to_list()
j = df['j'].to_list()
wij = df['wij'].to_list()

#建立函式 get_TableValue(x) 選取的 i,j 並用 mask列出我們需要的 i和 j
#用loc選取整個欄位 並找到我們要的 (i,j) return 那個值
def get_TableValue(x):
    i = x[0]
    j = x[1]
    mask = (df['i']==i) & (df['j']==j)
    target = df.loc[mask]['wij'].to_list()

    return target[0]

#建立一個zeros的矩陣，而且是一個(4639,4639)的矩陣
z = np.zeros([4693, 4693])

#建立迴圈 對x做 zip的元素打包 變成 tuple(類組) 並以(i,j)的形式呈現 因為前面以建成list的模式並不是tuple
#將對應得值扣除第一欄第一列(以變建立成需要的行列) 使這樣的迴圈 呼叫get_TableValue(x) 並執行這項
for x in tqdm(zip(i, j)):
    z[x[0]-1][x[1]-1] = get_TableValue(x)

# %%

91526it [03:42, 412.09it/s]

In [19]:
#檢查矩陣結果
print(z)

[[0.         0.2        0.         ... 0.         0.         0.        ]
 [0.2        0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.00917431 0.        ]
 [0.         0.         0.         ... 0.00917431 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [20]:
#讀檔變數矩陣
inpath1 = 'C:\\Users\\lol\\Desktop\\新北市七區研究\\新北市資料七區空間遞延\\板橋空間遞延\\變數矩陣\\板橋區WP.csv'
abc = pd.read_csv(inpath1)
abc

,logpdfs,pdfs,pdensity,inside,empty,income,freehigh,dishigh,dishigh2,fullhigh,...,stock,y102,y103,y104,y105,y106,season1,season2,season3,season4
0,1.167823,3.214985,66535.11690,0,0.0446,113.610639,0,4.002,16.016004,1,...,105.192,0,0,0,0,1,0,0,1,0
1,1.200534,3.321891,66535.11690,0,0.0446,113.610639,0,4.002,16.016004,1,...,105.948,0,0,0,0,1,0,0,1,0
2,1.578909,4.849661,28933.67543,1,0.0380,75.748691,0,6.273,39.350529,0,...,83.882,1,0,0,0,0,0,0,0,1
3,1.609053,4.998078,44322.05502,1,0.0492,88.906087,0,4.766,22.714756,0,...,79.424,1,0,0,0,0,0,1,0,0
4,1.631881,5.113483,23043.32309,1,0.0401,87.440453,1,5.571,31.036041,0,...,74.302,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4688,3.178418,24.008730,64698.54119,0,0.0785,120.980987,1,6.750,45.562500,0,...,79.428,1,0,0,0,0,0,1,0,0
4689,3.208967,24.753514,64698.54119,0,0.0487,120.980987,1,6.750,45.562500,0,...,97.497,0,0,1,0,0,1,0,0,0
4690,3.221029,25.053879,64698.54119,0,0.0572,120.980987,1,6.750,45.562500,0,...,87.138,0,1,0,0,0,1,0,0,0
4691,3.234081,25.383034,64698.54119,0,0.0487,120.980987,1,6.750,45.562500,0,...,95.794,0,0,1,0,0,1,0,0,0
4692,3.245593,25.676926,40841.90058,1,0.0481,97.914377,0,7.438,55.323844,1,...,81.350,1,0,0,0,0,0,1,0,0

In [21]:
bcd = z

In [22]:
#矩陣相成
arr = np.dot(bcd,abc)
arr

array([[2.34231017e+00, 1.17390298e+01, 6.65351169e+04, ...,
        6.00000000e-01, 2.00000000e-01, 2.00000000e-01],
       [2.33576783e+00, 1.17176484e+01, 6.65351169e+04, ...,
        6.00000000e-01, 2.00000000e-01, 2.00000000e-01],
       [2.33136506e+00, 1.02922421e+01, 2.89336754e+04, ...,
        9.98548067e-01, 4.29420301e-07, 1.44959656e-03],
       ...,
       [3.02664972e+00, 2.07363457e+01, 6.46985417e+04, ...,
        3.30275232e-01, 2.66055048e-01, 2.20183488e-01],
       [3.02652997e+00, 2.07333260e+01, 6.46985417e+04, ...,
        3.30275232e-01, 2.66055048e-01, 2.20183488e-01],
       [2.53007289e+00, 1.26584068e+01, 4.08419005e+04, ...,
        5.04499999e-01, 4.83052368e-01, 0.00000000e+00]])

In [23]:
#令矩陣為all_data
all_data = arr

In [24]:
#輸出檔案
pd.DataFrame(all_data).to_excel('板橋區50M Wp.xlsx')